# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NekoNihongo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NekoNihongo
  pod 'ASExtendedCircularMenu', :git => 'https://github.com/anshul18895/ASExtendedCircularMenu'
  pod 'Cartography'
  pod 'Device'

  target 'NekoNihongoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NekoNihongoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
